### ISSUE TITLE
Change code cell font in Jupyter PDF export

### ISSUE THREAD

**Issue by tysun** [ahrenberg/nbcorg#2]
I have edited the preamble of the article.tplx file to this. It changes all markdown to non-serif which is great.

```
((*- block docclass -*))
\documentclass[11pt]{article}
\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault}
((*- endblock docclass -*))
```

But the code cells font is still serif. Especially the ugly python comments.  Do you know if it's possible to change the code cell font?  Obviously the font originates from somewhere so there must be a way to change it either in a tplx file or original .py file somewhere in the library. The whole world is using the same ugly serif font for python code lol 

<img width="134" alt="latex" src="https://user-images.githubusercontent.com/11150198/83219293-f9761880-a1aa-11ea-876b-ae62afbf5bed.png">

**Comment by ahrenberg** [comment]
Very late reply (due to 2020 in general)... and this might not be an issue for you any more.
Anyway, I don't know very much about the PDF/LaTex export internals as this project is for orgmode export. The best I can say is that I *guess* that the PDF export via LaTeX uses [pygments](https://pygments.org/docs/) to typeset code. Perhaps worth checking those docs and the corresponding j2 template in nbconvert?
(You may want to check the official [nbconvert docs](https://nbconvert.readthedocs.io/en/latest/index.html) and [project](https://github.com/jupyter/nbconvert) for more information on adapting templates.) 

Hope this helps.
